# Generated by Django 4.2.6 on 2024-02-14 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_rename_image_image_image_file_product_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
